ensembl_gtf: /nfs/users/nfs_k/ka8/scratch/annotations/GRCh38/genes/Ensembl_87/Homo_sapiens.GRCh38.87.gtf
reference_genome: /nfs/users/nfs_k/ka8/scratch/annotations/GRCh38/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa 
salmon_ensembl_index: /nfs/users/nfs_k/ka8/scratch/annotations/GRCh38/genes/Ensembl_87/salmon_index_87
star_index: /nfs/users/nfs_k/ka8/scratch/annotations/GRCh38/STAR_index_87
vcf_file: /nfs/users/nfs_k/ka8/scratch/projects/macrophage-gxe-study/genotypes/acLDL/hipsci.wec.gtarray.HumanCoreExome-12_v1_0.858samples.20141111.genotypes.GRCh38.sorted.filtered.vcf.gz
chromosome_lengths: /lustre/scratch117/cellgen/team170/ka8/annotations/GRCh38/bt2-index/chromosome_lengths.txt
samples: [KOLF_2_FF_R848_6,KOLF_2_FF_IFNG_6,KOLF_2_FF_CILPS_6,KOLF_2_FF_sLPS_24,KOLF_2_FF_P3C_6,KOLF_2_FF_CILPS_24,KOLF_2_FF_Ctrl_24,KOLF_2_FF_R848_24,KOLF_2_FF_sLPS_6,KOLF_2_FF_Salb_24,KOLF_2_FF_Ctrl_6,KOLF_2_FF_IL4_24,KOLF_2_FF_IFNB_24,KOLF_2_FF_IL10_24,KOLF_2_FF_TPP_24,KOLF_2_FF_P3C_24,KOLF_2_FF_CI_6,KOLF_2_FF_CI_24,KOLF_2_FF_TPP_6,KOLF_2_FF_IFNB_6,KOLF_2_FF_IL4_6,KOLF_2_FF_IL10_6,KOLF_2_FF_Salb_6,KOLF_2_FF_IFNG_24]
annotations: ["reviseAnnotations_contained","reviseAnnotations_downstream","reviseAnnotations_upstream"]
study: macroMap

#Quantification
leafcutter_root: "/nfs/users/nfs_k/ka8/software/leafcutter"

#QTL mapping 
conditions: ["Ctrl", "AcLDL", "Diff"]
n_batches: 250
qtl_vcf: "/nfs/users/nfs_k/ka8/scratch/projects/macrophage-gxe-study/genotypes/acLDL/imputed_20151005/imputed.70_samples.sorted.filtered.named.INFO_07.vcf.gz"
cis_window: 100000
annot_type: ["ensembl_87", "reviseAnnotations", "leafcutter"]



