#Colocalisation
coloc_phenotypes: ["SL1344", "ATAC"]
gwas_dir: "/nfs/users/nfs_k/ka8/scratch/datasets/Inflammatory_GWAS/"
coloc_window: 2e5
gwas_traits: ["AD","CEL_2010","CEL","CD_2012","CD","IBD","UC","MS","NAR","PBC","PS","RA_2012","RA","SCZ","SLE","T1D","T1D_2","T2D_1","T2D","UC_2012","UC_2014","CAD","MI","CRE","CRP","GLU","HDL","HGB","HOMA_b","HOMA_ir","IL6","INS","MCHC","MCH","MCV","PCV","PLT","RBC","TC","TG","UA","WBC","LDL"]

